apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-frontend
  labels:
    account: sa-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: sa-frontend
  labels:
    app: sa-frontend
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: sa-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-frontend
  labels:
    app: sa-frontend
    version: white
spec:
  selector:
    matchLabels:
      app:  sa-frontend
      version: white
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sa-frontend
        version: white
    spec:
      serviceAccountName: sa-frontend
      containers:
      - image: rinormaloku/sentiment-analysis-frontend:istio
        imagePullPolicy: Always
        name: sa-frontend
        ports:
        - containerPort: 80
---
