apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-feedback
  labels:
    account: sa-feedback
---
apiVersion: v1
kind: Service
metadata:
  name: sa-feedback
  labels:
    app: sa-feedback
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: sa-feedback
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-pvc
  labels:
    app: sa-feedback
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-feedback
  labels:
    app: sa-feedback
    version: v1
spec:
  selector:
    matchLabels:
      app: sa-feedback
      version: v1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sa-feedback
        version: v1
    spec:
      serviceAccountName: sa-feedback
      containers:
      - image: rinormaloku/sentiment-analysis-feedback:istio-mastery
        imagePullPolicy: Always
        name: sa-feedback
        env:
        - name: DATABASE_DIR
          value: /usr/db
        ports:
          - containerPort: 80
        volumeMounts:
        - name: sqlite-volume
          mountPath: /usr/db
      volumes:
      - name: sqlite-volume
        persistentVolumeClaim:
          claimName: sqlite-pvc
---
