apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-logic
  labels:
    account: sa-logic
---
apiVersion: v1
kind: Service
metadata:
  name: sa-logic
  labels:
    app: sa-logic
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5000
  selector:
    app: sa-logic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-logic
  labels:
    app: sa-logic
    version: v1
spec:
  selector:
    matchLabels:
      app:  sa-logic
      version: v1
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: sa-logic
        version: v1
    spec:
      serviceAccountName: sa-logic
      containers:
      - image: rinormaloku/sentiment-analysis-logic:istio-mastery
        imagePullPolicy: Always
        name: sa-logic
        env:
        - name: FAIL_RANDOMLY
          value: "false"
        ports:
        - containerPort: 5000
